spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cs209
    username: root
    password: Maintank1314!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/project/mapper/xml/*.xml

server:
  port: 8181
